export const testData = {
    "content":
    [
        {"bindingID":"ce081440-82a9-11e8-9b5b-3bfd459ee839",
         "settings":null,
         "condition":[{"lon":139,"lat":35,"value":"isday"}],
         "status":false,
         "command":null,
         "category":"dalylight",
         "dateCreated":"2018-07-15T17:26:00.328+0000",
         "conditionAsCondition":{"lon":139.0,"lat":35.0,"value":"is_day","conditionType":"WEATHER"}
        },
        {"bindingID":"ce081440-82a9-3349-9b5b-3bfd459ee866",
         "settings":null,
         "condition":[{"lon":139,"lat":35,"value":"isnight"}],
         "status":false,
         "command":null,
         "category":"daylight",
         "dateCreated":"2018-07-15T17:29:00.328+0000",
         "conditionAsCondition":{"lon":139.0,"lat":35.0,"value":"is_night","conditionType":"WEATHER"}
        }
        ],
    "pageable":
        {"sort":{"sorted":false,"unsorted":true},
        "pageSize":5,
        "pageNumber":1,
        "offset":5,
        "paged":true,
        "unpaged":false
        },
    "last":true,
    "totalPages":2,
    "totalElements":2,
    "first":false,
    "sort":{"sorted":false,"unsorted":true},"numberOfElements":2,"size":5,"number":1}